name: Roman Converter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (solo si en el futuro usas npm)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (skipped, not needed)

      - name: Run HTML tests in headless browser
        uses: coactions/setup-xvfb@v1
      - name: Run test.html with headless browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --headless --disable-gpu --no-sandbox --dump-dom test.html > result.html
          cat result.html | grep PASSED || true  # Para visualizar resultados

      - name: Deploy paginaWeb.html to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
